Repository fleencorp/fleen-feen, pull requests merged in 2024-11, with the labels that each got.

#88 Refactor Entity Fields, Service Implementations, and Utility Methods for Improved Maintainability and Performance
  src/main/java/com/fleencorp/feen/constant/base/ReportMessageType.java
  src/main/java/com/fleencorp/feen/constant/external/google/GoogleOauth2Scopes.java
  src/main/java/com/fleencorp/feen/constant/external/google/oauth2/Oauth2Source.java
  src/main/java/com/fleencorp/feen/constant/external/google/oauth2/Oauth2WebKey.java
  src/main/java/com/fleencorp/feen/constant/http/FleenHttpStatus.java
  src/main/java/com/fleencorp/feen/constant/http/StatusCodeMessage.java
  src/main/java/com/fleencorp/feen/constant/message/ResponseMessage.java
  src/main/java/com/fleencorp/feen/exception/google/oauth2/Oauth2AuthorizationException.java
  src/main/java/com/fleencorp/feen/mapper/CalendarMapper.java
  src/main/java/com/fleencorp/feen/mapper/ContactMapper.java
  src/main/java/com/fleencorp/feen/mapper/FleenStreamMapper.java
  src/main/java/com/fleencorp/feen/mapper/FollowerMapper.java
  src/main/java/com/fleencorp/feen/mapper/external/GoogleCalendarMapper.java
  src/main/java/com/fleencorp/feen/model/domain/auth/Oauth2Authorization.java
  src/main/java/com/fleencorp/feen/model/domain/social/Contact.java
  src/main/java/com/fleencorp/feen/model/domain/user/Member.java
  src/main/java/com/fleencorp/feen/model/dto/social/contact/AddContactDto.java
  src/main/java/com/fleencorp/feen/model/dto/user/profile/SendUpdateEmailAddressOrPhoneNumberVerificationCodeDto.java
  src/main/java/com/fleencorp/feen/model/request/Oauth2AuthenticationRequest.java
  src/main/java/com/fleencorp/feen/model/request/auth/CompletedUserSignUpRequest.java
  src/main/java/com/fleencorp/feen/model/request/chat/space/CreateChatSpaceRequest.java
  src/main/java/com/fleencorp/feen/model/request/verification/SendVerificationCodeRequest.java
  src/main/java/com/fleencorp/feen/model/response/external/google/calendar/calendar/GoogleCreateCalendarResponse.java
  src/main/java/com/fleencorp/feen/model/security/FleenUser.java
  src/main/java/com/fleencorp/feen/service/impl/auth/AuthenticationServiceImpl.java
  src/main/java/com/fleencorp/feen/service/impl/common/CacheKeyService.java
  src/main/java/com/fleencorp/feen/service/impl/external/aws/StorageService.java
  src/main/java/com/fleencorp/feen/service/impl/external/google/oauth2/GoogleOauth2Service.java
  src/main/java/com/fleencorp/feen/service/impl/stream/LiveBroadcastServiceImpl.java
  src/main/java/com/fleencorp/feen/service/impl/stream/base/StreamService.java
  src/main/java/com/fleencorp/feen/service/impl/user/MemberServiceImpl.java
  src/main/java/com/fleencorp/feen/service/user/MemberService.java
  src/main/java/com/fleencorp/feen/util/security/UserAuthoritiesUtil.java
Labels: bug, documentation, enhancement, test

#89 Refactoring and enhancement
  src/main/java/com/fleencorp/feen/configuration/security/SecurityConfiguration.java
  src/main/java/com/fleencorp/feen/constant/base/SimpleConstant.java
  src/main/java/com/fleencorp/feen/exception/RestExceptionHandler.java
  src/main/java/com/fleencorp/feen/i18n/Messages.java
  src/main/java/com/fleencorp/feen/mapper/ContactMapper.java
  src/main/java/com/fleencorp/feen/mapper/CountryMapper.java
  src/main/java/com/fleencorp/feen/mapper/external/GoogleCalendarEventMapper.java
  src/main/java/com/fleencorp/feen/service/impl/notification/NotificationServiceImpl.java
  src/main/java/com/fleencorp/feen/service/impl/security/mfa/MfaServiceImpl.java
  src/main/java/com/fleencorp/feen/service/impl/user/MemberServiceImpl.java
  src/main/java/com/fleencorp/feen/util/DateTimeUtil.java
  src/main/java/com/fleencorp/feen/util/external/google/GoogleApiUtil.java
  src/main/java/com/fleencorp/feen/util/security/Oauth2Util.java
Labels: documentation, enhancement

#92 Refactor Event and Stream Management, Bug Fixes, and Localization Enhancements
  src/main/java/com/fleencorp/feen/constant/stream/IsDeleted.java
  src/main/java/com/fleencorp/feen/constant/stream/StreamStatus.java
  src/main/java/com/fleencorp/feen/mapper/FleenStreamMapper.java
  src/main/java/com/fleencorp/feen/model/domain/stream/FleenStream.java
  src/main/java/com/fleencorp/feen/model/info/IsDeletedInfo.java
  src/main/java/com/fleencorp/feen/model/info/IsForKidsInfo.java
  src/main/java/com/fleencorp/feen/model/info/stream/StreamStatusInfo.java
  src/main/java/com/fleencorp/feen/model/response/event/DeletedEventResponse.java
  src/main/java/com/fleencorp/feen/model/response/event/UpdateEventVisibilityResponse.java
  src/main/java/com/fleencorp/feen/model/response/stream/base/FleenStreamResponse.java
  src/main/java/com/fleencorp/feen/service/impl/stream/EventServiceImpl.java
  src/main/resources/db/initialization/db.changelog-create-schema.sql
  src/main/resources/i18n/messages_en_US.properties
  src/main/resources/i18n/messages_fr.properties
Labels: bug, documentation, enhancement

#93 Added final modifier to method parameters & variables
  src/main/java/com/fleencorp/feen/service/impl/user/MemberServiceImpl.java
Labels: documentation, enhancement
